language: python
virtualenv:
  system_site_packages: true
python:
  - "2.7"
# command to install dependencies
install: 
  - gcc -v
  - mkdir build
  - cmake .. -DCOOLPROP_TESTING=ON
  - cmake .. -DCOOLPROP_TESTING=ON
  - make
  - ctest
# command to run tests
script: 
  - pwd
  - cd $TRAVIS_BUILD_DIR/wrappers/Python/CoolProp/tests
  - nosetests

notifications:
  email:
    recipients:
      - rodney.persky@gmail.com
    on_success: never # default: change
    on_failure: always # default: always
