language: python
virtualenv:
  system_site_packages: true
python:
  - "2.7"

install: 
  - gcc -v
  - mkdir build
  - cd build
  - cmake .. -DCOOLPROP_TESTING=ON
  - make

script: 
  - pwd
  - cd $TRAVIS_BUILD_DIR/build
  - ctest

notifications:
  email:
    recipients:
      - rodney.persky@gmail.com
    on_success: never # default: change
    on_failure: always # default: always
