language: c++
compiler:
  - gcc
  - clang

before_install:
  - sudo apt-get install -qq python-numpy

before_script: 
  - gcc -v
  - mkdir build
  - cd build
  - cmake .. -DCOOLPROP_TESTING=ON -DCMAKE_BUILD_TYPE=Debug
  - make

script: 
  - pwd
  - cd $TRAVIS_BUILD_DIR/build
  - ctest -VV

notifications:
  email:
    recipients:
      - rodney.persky@gmail.com
    on_success: never # default: change
    on_failure: always # default: always
