
version: 'CoolProp.{build}'

# branches to build
branches:
  # blacklist
  except:
    - coverity_scan

environment:
  matrix:
    #- APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
    #  CMAKE_GENERATOR: Visual Studio 15 2017 Win64
    #- APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
    #  CMAKE_GENERATOR: Visual Studio 15 2017
    #- APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
    #  CMAKE_GENERATOR: Visual Studio 14 2015 Win64
    #- APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
    #  CMAKE_GENERATOR: Visual Studio 14 2015
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2013
      CMAKE_GENERATOR: Visual Studio 12 2013 ARM
      BUILD_ARGS: --target coolprop_library --config Debug
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2013
      CMAKE_GENERATOR: Visual Studio 12 2013 Win64
      BUILD_ARGS: --target coolprop_library --config Debug
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2013
      CMAKE_GENERATOR: Visual Studio 12 2013
      BUILD_ARGS: --target coolprop_library --config Debug

install:
  - cmd: git submodule update --init --recursive
    
before_build:
  - cmd: mkdir build && cd build && cmake .. -G"%CMAKE_GENERATOR%"

#build:
#  - project: $(APPVEYOR_BUILD_FOLDER)\build\$(APPVEYOR_PROJECT_NAME).sln

build_script: 
  #- cmd: cd %APPVEYOR_BUILD_FOLDER%\build && cmake --build . %BUILD_ARGS%
  - cmd: cmake --build . %BUILD_ARGS%
