# Tell appveyor to not use msbuild
build: false

environment:
  matrix:
    - PYTHON_VERSION: 2.7
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
    - PYTHON_VERSION: 3.5
    - PYTHON_VERSION: 3.6
    - PYTHON_VERSION: 3.7
    - PYTHON_VERSION: 3.8

platform:
  - x86
  - x64

init:
  - ECHO %PYTHON_VERSION% - %Platform%
  - SET PYTHON_MAJOR_VERSION=%PYTHON_VERSION:~0,1%
  #- IF %PYTHON_MAJOR_VERSION% == 2 SET WIN_SDK_VERSION=v7.0
  #- IF %PYTHON_MAJOR_VERSION% == 3 SET WIN_SDK_VERSION=v7.1
  #- ECHO Configuring Windows SDK %WIN_SDK_VERSION% for Python %PYTHON_MAJOR_VERSION% on an %Platform% platform
  #- CALL "C:\Program Files\Microsoft SDKs\Windows\%WIN_SDK_VERSION%\Setup\WindowsSdkVer.exe" -q -version:%WIN_SDK_VERSION%
  #- CALL "C:\Program Files\Microsoft SDKs\Windows\%WIN_SDK_VERSION%\Bin\SetEnv.cmd" /%Platform% /release

install:
  - git submodule update --init --recursive
  - IF "%Platform%"=="x86" ( CALL "C:\Miniconda37\Scripts\activate.bat" )
  - IF "%Platform%"=="x64" ( CALL "C:\Miniconda37-x64\Scripts\activate.bat" )
  - conda create -y -n condaenv python=%PYTHON_VERSION% cython pip requests jinja2 pyyaml wheel
  - conda activate condaenv
  - IF "%PYTHON_VERSION%"=="2.7" ( conda install -y ndg-httpsclient )
  - conda deactivate

build_script:
  - CD wrappers\Python
  - IF "%Platform%"=="x86" ( CALL "C:\Miniconda37\Scripts\activate.bat" )
  - IF "%Platform%"=="x64" ( CALL "C:\Miniconda37-x64\Scripts\activate.bat" )
  - conda activate condaenv
  - python generate_meta_info.py
  #- IF "%Platform%"=="x86" IF "%PYTHON_VERSION%"=="2.7" ( python setup.py bdist_wheel --dist-dir ../../install_root/Python bdist_wininst --dist-dir ../../install_root/Python --cmake-compiler vc9 --cmake-bitness 32 )
  #- IF "%Platform%"=="x64" IF "%PYTHON_VERSION%"=="2.7" ( python setup.py bdist_wheel --dist-dir ../../install_root/Python bdist_wininst --dist-dir ../../install_root/Python --cmake-compiler vc9 --cmake-bitness 64 )
  #- IF NOT "%PYTHON_VERSION%"=="2.7"                    ( python setup.py bdist_wheel --dist-dir ../../install_root/Python bdist_wininst --dist-dir ../../install_root/Python )
  - python setup.py bdist_wheel --dist-dir ../../install_root/Python bdist_wininst --dist-dir ../../install_root/Python
  - python setup.py clean
  - conda deactivate

# deploy_script:
  # - DIR
  # - CD ../../install_root
  # - DIR
  # - CD Python
  # - DIR

artifacts:
  - path: '..\..\install_root\Python\*.whl'
    name: pythonwheels

deploy:
  - provider: BinTray
    username: jowr
    api_key:
      secure: KNBl77nxs4FijM/Ycjf3GkX0UsLDZrD0loNMB3hWPZWCsRt/Wq5lVh+mbOlujLGO
    subject: coolprop
    repo: ci_binaries
    package: Python
    #version: version
    #publish: false
    #override: true
    #explode: true
    artifact: pythonwheels
