
name: PythonWheels

on: [push]

#on:
#  push:
#    branches: [ master ]
#  pull_request:
#    branches: [ master ]

jobs:
  build_linux:

    runs-on: ${{ matrix.os }}
    #strategy:
    #  matrix:
    #    os: [windows-latest, ubuntu-latest, macOS-latest]
    #    python-version: [3.5, 3.6, 3.7, 3.8]
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: [3.8]
        bitness: [32, 64]

    steps:
    - name: Checkout from git
      uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    #- name: Build the package
    #  shell: bash
    #  working-directory: "wrappers/Python/manylinux"
    #  run: |
    #    chmod +x 00_prepare_docker.sh
    #    ./00_prepare_docker.sh 64
    - name: Build the package
      shell: bash
      working-directory: "wrappers/Python/manylinux"
      run: |
        BITNESS=${{ matrix.bitness }}
        if [[ "$BITNESS" == "64" ]] 
        then
            DOCKER_IMG_NAME="coolprop/manylinux"
            SETUP_PY_ARGS="cmake=default,64"
        elif [[ "$BITNESS" == "32" ]] 
        then
            DOCKER_IMG_NAME="coolprop/manylinux32"
            SETUP_PY_ARGS="cmake=default,32"
        else
            echo "Received an unknown argument, aborting."
            exit 1
        fi
        DOCKER_MACHINE_TAG="v2.1.0"
        # Get the directory containing this script
        # see http://stackoverflow.com/a/246128/1360263
        CUR_DIR="$( pwd )"
        # Go up three directories
        pushd ${CUR_DIR}/../../..
        # Run the build script
        chmod +x ${CUR_DIR}/01_build_wheels.sh
        # Remove the manylinux container if it didn't complete properly last time (see also https://stackoverflow.com/a/38225298/1360263)
        docker stop manylinux || true && docker rm manylinux || true
        docker run -itd --name manylinux ${DOCKER_IMG_NAME}:${DOCKER_MACHINE_TAG} bash
        docker cp . manylinux:/io
        docker exec manylinux /io/wrappers/Python/manylinux/01_build_wheels.sh ${SETUP_PY_ARGS}
        docker cp manylinux:/io/install_root install_root
        docker stop manylinux 
        docker rm manylinux
        popd
    - name: Upload wheels
      uses: actions/upload-artifact@v2
      with:
        name: PythonWheels
        path: install_root


  build_other:

    runs-on: ${{ matrix.os }}
    #strategy:
    #  matrix:
    #    os: [windows-latest, ubuntu-latest, macOS-latest]
    #    python-version: [3.5, 3.6, 3.7, 3.8]
    strategy:
      matrix:
        os: [windows-latest, macOS-latest]
        python-version: [3.8]
        architecture: [x86, x64]
        exclude:
          - os: macOS-latest
            architecture: x86

    steps:
    - name: Checkout from git
      uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
        architecture: ${{ matrix.architecture }}
    - name: Install dependencies
      shell: bash
      working-directory: "wrappers/Python"
      #run: |
      #  python -m pip install --upgrade pip
      #  pip install flake8 pytest
      #  if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      run: |
        pip install --upgrade pip
        pip install flake8 pytest
        pip install cython requests jinja2 pyyaml pycrypto wheel
      
    #- name: Lint with flake8
    #  shell: bash
    #  working-directory: "wrappers/Python"
    #  run: |
    #    # stop the build if there are Python syntax errors or undefined names
    #    flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
    #    # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
    #    flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    #- name: Test with pytest
    #  run: |
    #    pytest
    
    - name: Build the package
      shell: bash
      working-directory: "wrappers/Python"
      run: |
        python generate_meta_info.py
        python setup.py bdist_wheel --dist-dir ../../install_root/Python bdist_wininst --dist-dir ../../install_root/Python
        python setup.py clean
        
        
        
    - name: Upload wheels
      uses: actions/upload-artifact@v2
      with:
        name: PythonWheels
        path: install_root
